### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by torarnv** [cxnder/bn-dyldsharedcache#10]
Tried this just now, and got this, trying to extract the macOS 13.1 x86_64h cache:
```
Successfully installed: Dyld Shared Cache Processor
Loaded python3 plugin 'cxnder_bndyldsharedcache'
Traceback (most recent call last):
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py", line 2818, in _init
    return self.init()
  File "/Users/torarne/Library/Application Support/Binary Ninja/repositories/community/plugins/cxnder_bndyldsharedcache/dsc.py", line 101, in init
    stub_fixer.fixStubs(extraction_ctx)
  File "/Users/torarne/Library/Application Support/Binary Ninja/repositories/community/plugins/cxnder_bndyldsharedcache/DyldExtractor/converter/stub_fixer.py", line 1681, in fixStubs
    _StubFixer(extractionCtx).run()
  File "/Users/torarne/Library/Application Support/Binary Ninja/repositories/community/plugins/cxnder_bndyldsharedcache/DyldExtractor/converter/stub_fixer.py", line 1011, in run
    self._symbolizer = _Symbolizer(self._extractionCtx)
  File "/Users/torarne/Library/Application Support/Binary Ninja/repositories/community/plugins/cxnder_bndyldsharedcache/DyldExtractor/converter/stub_fixer.py", line 59, in __init__
    self._enumerateExports()
  File "/Users/torarne/Library/Application Support/Binary Ninja/repositories/community/plugins/cxnder_bndyldsharedcache/DyldExtractor/converter/stub_fixer.py", line 101, in _enumerateExports
    if depInfo := self._getDepInfo(dylib, self._machoCtx):
  File "/Users/torarne/Library/Application Support/Binary Ninja/repositories/community/plugins/cxnder_bndyldsharedcache/DyldExtractor/converter/stub_fixer.py", line 179, in _getDepInfo
    imageOff, dyldCtx = self._dyldCtx.convertAddr(imageAddr)
TypeError: cannot unpack non-iterable NoneType object
BinaryView of type 'DyldSharedCache' failed to initialize!
No available/valid debug info parsers for `Raw` view
Found more than 'analysis.limits.stringSearch' (0x100000) strings aborting search for range: 0 - 0x33be0000
Analysis update took 12.239 seconds

```

**Comment by 0cyn** [comment]
This particular plugin is built entirely off of other smaller projects, and as such only supports <= iOS 14 shared caches. tooling to support all formats across all platforms is being tracked here: https://github.com/Vector35/binaryninja-api/issues/290 .
